version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
    - 5.35.1
  - dependency-name: d3
    versions:
    - 6.6.0
    - 6.6.1
    - 6.6.2
    - 6.7.0
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: vue-resource
    versions:
    - 1.5.2
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: bulma
    versions:
    - 0.9.2
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: github.com/olekukonko/tablewriter
    versions:
    - 0.0.5
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.3
